repos:
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        files: \.py$
        args: [
          --rcfile=.pylintrc
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: \.py$
        args: [
          --config-file=mypy.ini
        ]
